version: '3.8'

services:
  postgres-test:
    image: postgres:17.0-alpine
    container_name: reginae-sanguine-postgres-test
    environment:
      POSTGRES_DB: reginae_sanguine_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-test-data:
