[versions]
flyway = "11.15.0"
kotlin = "2.2.21"
compose = "1.9.2"
arrow = "2.2.0"
kotest = "6.0.4"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
mockk = "1.14.6"
mosaic = "0.18.0"
coil = "3.3.0"
postgresql = "42.7.8"
testcontainers = "1.21.3"
spring-boot = "4.0.0-RC1"
spring-dependency-management = "1.1.7"

# Android dependencies
android = "8.11.1"
appcompat = "1.7.1"
lifecycle = "2.9.4"
activity-compose = "1.11.0"

# Build plugins
ktlint = "13.1.0"
kover = "0.9.3"
download = "5.6.0"
task-tree = "4.0.1"

[libraries]
# Kotlinx
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines"}

# Arrow-kt
arrow-stack = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrow" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core" }

# Kotest
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest-extensions-testcontainers = { module = "io.kotest:kotest-extensions-testcontainers", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-framework-engine = { group = "io.kotest", name = "kotest-framework-engine", version.ref = "kotest" }

# Coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

# Android
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

# Database
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

# Third-party
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mosaic-runtime = { group = "com.jakewharton.mosaic", name = "mosaic-runtime", version.ref = "mosaic" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

android-application = { id = "com.android.application", version.ref = "android" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }

ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
download = { id = "de.undercouch.download", version.ref = "download" }
task-tree = { id = "com.dorongold.task-tree", version.ref = "task-tree" }